"""create_prekey_bundles

Revision ID: 0081668158d9
Revises: 0001
Create Date: 2026-07-13 16:36:08.593808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0081668158d9"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prekey_bundles",
        sa.Column("onion_address", sa.String(length=128), nullable=False),
        sa.Column("identity_key", sa.Text(), nullable=False),
        sa.Column("signed_prekey", sa.Text(), nullable=False),
        sa.Column("signed_prekey_sig", sa.Text(), nullable=False),
        sa.Column("pq_prekey", sa.Text(), nullable=False),
        sa.Column("pq_prekey_sig", sa.Text(), nullable=False),
        sa.Column(
            "one_time_prekeys_json", sa.Text(), nullable=False, server_default="[]"
        ),
        sa.Column(
            "one_time_pq_prekeys_json", sa.Text(), nullable=False, server_default="[]"
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("onion_address"),
    )
    op.create_index(
        "ix_prekey_bundles_onion_address",
        "prekey_bundles",
        ["onion_address"],
        unique=False,
    )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_contacts_owner_onion_users",
            "users",
            ["owner_onion"],
            ["onion_address"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.alter_column(
            "group_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_group_members_group_id"), ["group_id"], unique=False
        )

    with op.batch_alter_table("group_messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.alter_column(
            "message_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "group_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_group_messages_message_id"), ["message_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_group_messages_sent_at"), ["sent_at"], unique=False
        )

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.alter_column(
            "group_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_groups_group_id"), ["group_id"], unique=True
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.alter_column(
            "message_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "iv_b64",
            existing_type=sa.VARCHAR(length=44),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_messages_sender_recipient"))
        batch_op.create_index(
            batch_op.f("ix_messages_message_id"), ["message_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_messages_recipient_onion"), ["recipient_onion"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_sender_onion"), ["sender_onion"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_column("last_seen")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_sender_onion"))
        batch_op.drop_index(batch_op.f("ix_messages_recipient_onion"))
        batch_op.drop_index(batch_op.f("ix_messages_message_id"))
        batch_op.create_index(
            batch_op.f("ix_messages_sender_recipient"),
            ["sender_onion", "recipient_onion"],
            unique=False,
        )
        batch_op.alter_column(
            "iv_b64",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=44),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "message_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_group_id"))
        batch_op.alter_column(
            "group_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    with op.batch_alter_table("group_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_messages_sent_at"))
        batch_op.drop_index(batch_op.f("ix_group_messages_message_id"))
        batch_op.alter_column(
            "group_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "message_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_members_group_id"))
        batch_op.alter_column(
            "group_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_contacts_owner_onion_users", type_="foreignkey")

    op.drop_index("ix_prekey_bundles_onion_address", table_name="prekey_bundles")
    op.drop_table("prekey_bundles")

    # ### end Alembic commands ###
