"""create_v3_settings_and_notifications

Revision ID: 71b9e6fd267b
Revises: 0081668158d9
Create Date: 2026-07-13 21:58:36.087645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71b9e6fd267b"
down_revision: Union[str, Sequence[str], None] = "0081668158d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notify_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notify_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notify_queue_token"), ["token"], unique=False
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notify_queue_token", sa.Text(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("preferred_file_relay", sa.String(length=512), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferred_file_relay")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_column("notify_queue_token")

    with op.batch_alter_table("notify_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notify_queue_token"))

    op.drop_table("notify_queue")
    # ### end Alembic commands ###
