"""add_contact_keys_and_status

Revision ID: 780ce35d17d9
Revises: 71b9e6fd267b
Create Date: 2026-07-14 09:16:52.457656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "780ce35d17d9"
down_revision: Union[str, Sequence[str], None] = "71b9e6fd267b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("contacts")]

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        if "status" not in columns:
            batch_op.add_column(
                sa.Column(
                    "status",
                    sa.String(length=32),
                    nullable=False,
                    server_default="accepted",
                )
            )
        if "public_key_b64" not in columns:
            batch_op.add_column(sa.Column("public_key_b64", sa.Text(), nullable=True))
        if "shared_secret_b64" not in columns:
            batch_op.add_column(
                sa.Column("shared_secret_b64", sa.Text(), nullable=True)
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_column("shared_secret_b64")
        batch_op.drop_column("public_key_b64")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
